title = "Floraud"
baseURL = "https://floraud.fr"
languageCode = "fr"
# Dossier dans lequel seront stockés des fichiers optimisés que Hugo traite en interne
resourceDir = "../resources"
# La description ci-dessous aide à la description des metadata
description = "Blog personnel sur la tech et mes autres passions"

DefaultContentLanguage = "fr"
# Commenter la section du dessous permet de ne pas reprendre automatiquement les dossiers comme "content/postes/"
# SectionPagesMenu = "main"

# Nombre d'article par page
pagination.pagerSize = 9
enableRobotsTXT = true

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[sitemap]
  # Permet au moteur de recherche d'indexer plus efficacement le site en suivant les consignes
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  favicon = ""
  site_logo = ""
  # La description ci-dessous permet de reprendre ce paramètre dans un template
  description = "Le blog d'un passionné d'informatique à propos de ses loisirs"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[params.ananke.social.networks.git]
label = "Git"
profile = "https://git.floraud.fr/floraud"
icon = "git-alt" 

[params.ananke.social]
  [params.ananke.social.follow]
  new_window_icon = true
  networks = [
  "git",
  "github"
  ]

[params.ananke.social.github]
username = "floraud"

# [params.ananke.social.share]
# icons = true
# sharetext = true
# networks = [
#   "email",
#   "linkedin",
#   "mastodon",
#   "facebook",
# ]

[[menu.main]]
   name = "Tech"
   url = "/categories/tech/"
   weight = 10

[[menu.main]]
  name = "Maison"
  url = "/categories/maison/"
  weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"
